# Generated by Django 4.1.3 on 2022-12-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registers',
            name='user_type',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
