# Generated by Django 4.1.3 on 2022-12-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_registers_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('otp', models.IntegerField()),
            ],
            options={
                'db_table': 'otp_verification',
            },
        ),
    ]
