# Generated by Django 4.1.3 on 2022-12-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_alter_category_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('company', models.TextField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('model', models.TextField(max_length=50)),
                ('display_size', models.IntegerField()),
                ('description', models.TextField(max_length=150)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
