# Generated by Django 4.1.3 on 2022-12-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='display_size',
            field=models.TextField(max_length=50),
        ),
    ]
