# Generated by Django 4.1.3 on 2022-12-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_alter_product_display_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='display_size',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(max_length=50),
        ),
    ]
