# Generated by Django 4.1.3 on 2022-12-16 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0015_alter_productimage_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='product_id',
            new_name='product',
        ),
    ]
