# Generated by Django 4.1.3 on 2022-12-21 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0020_order'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
    ]
